### PR TITLE
Failing testcase for prototype property named attributes

### PR DESCRIPTION
**Pull request by tmcw**
:(

Bug inspiration & the associated fix: https://github.com/documentationjs/documentation/pull/396

### CODE REVIEW

**Comment by scothis** [comment]
good old `Object.create(null)`

**Comment by davidtheclark** [comment]
@tmcw Interesting phenomenon, that is.

This package needs to support Node 0.10 until we upgrade unpacker to v4, and it looks like 0.10 does not support the `Object.create(null)` behavior: http://node.green. Can try to accommodate another way, though ...

**Comment by scothis** [comment]
`Object.create` is ES5 it will work in Node 0.10.

**Comment by davidtheclark** [comment]
Ah, I misread the limitation, which is more obscure than just `Object.create(null)` not doing what we want ...

**Pull request merged**
